### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2021_Psi-Ascii-#4]
If you want me to correct the repository name (it was generated automatically and Serbian characters were removed since they cannot be in the repository title), write here.

**Comment by idzii** [comment]
That would be great. PsicAsciic sounds much better than Psi_Ascii_. Please correct it for us.

**Comment by ivan-ristovic** [comment]
Done, this will make old repository URLs obsolete some time in the future, not sure how long until that becomes the case.
